=== dimonn12/LabTask6/LabTask6-web/src/main/resources/xml/products.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/Products"
	elementFormDefault="unqualified" xmlns:products="http://www.example.org/Products">

	<element name="categoryList">
		<complexType>
			<sequence>
				<element name="category" type="products:category" maxOccurs="unbounded"
					minOccurs="1" />
			</sequence>
		</complexType>
	</element>

	<complexType name="category">
		<sequence>
			<element name="subcategory" type="products:subcategory"
				maxOccurs="unbounded" minOccurs="1" />
		</sequence>
		<attribute name="name" use="required" />
	</complexType>

	<complexType name="subcategory">
		<sequence>
			<element name="product" type="products:product" maxOccurs="unbounded"
				minOccurs="1" />
		</sequence>
		<attribute name="name" use="required" />
	</complexType>

	<complexType name="product">
		<sequence>
			<element name="provider" type="products:provider" minOccurs="1" maxOccurs="1"/>
			<element name="model" type="products:model" minOccurs="1" maxOccurs="1"/>
			<element name="color" type="products:color" minOccurs="1" maxOccurs="1"/>
			<element name="date" type="products:date" minOccurs="1" maxOccurs="1"/>			
			<choice>
				<element name="price" type="products:price" minOccurs="1" maxOccurs="1"/>
				<element name="notInStock" type="products:notInStock" minOccurs="1" maxOccurs="1"/>
			</choice>
		</sequence>
		<attribute name="name" use="required" />
	</complexType>

	<simpleType name="model">
		<restriction base="string" />
	</simpleType>

	<simpleType name="date">
		<restriction base="string">
			<pattern
				value="(0[1-9]|[12][0-9]|3[01])[-](0[1-9]|1[012])[-]((19|20)[0-9]{2})" />
		</restriction>
	</simpleType>

	<simpleType name="provider">
		<restriction base="string" />
	</simpleType>

	<simpleType name="color">
		<restriction base="string" />
	</simpleType>

	<simpleType name="price">
		<restriction base="double" />
	</simpleType>

	<simpleType name="notInStock">
		<restriction base="string" />
	</simpleType>

</schema>

=== dimonn12/LabTask6/LabTask6-web/src/main/resources/xml/products.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- <!DOCTYPE categoryList SYSTEM "products.dtd"> -->

<products:categoryList xmlns:products="http://www.example.org/Products"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/Products products.xsd">

	<category name="Category1">
		<subcategory name="Subcategory11">
			<product name="Product111">
				<provider>Provider111</provider>
				<model>Model111</model>
				<color>Color111</color>
				<date>01-01-2001</date>
				<notInStock/>
			</product>
			<product name="Product112">
				<provider>Provider112</provider>
				<model>Model112</model>
				<color>Color112</color>
				<date>03-03-2003</date>
				<price>101.01</price>
			</product>
			<product name="Product113">
				<provider>Provider113</provider>
				<model>Model113</model>
				<color>Color113</color>
				<date>03-05-2003</date>
				<price>113.00</price>
			</product>
		</subcategory>
		<subcategory name="Subcategory12">
			<product name="Product121">
				<provider>Provider121</provider>
				<model>Model121</model>
				<color>Color121</color>
				<date>25-12-2001</date>
				<price>121.12</price>
			</product>
			<product name="Product122">
				<provider>Provider122</provider>
				<model>Model122</model>
				<color>Color122</color>
				<date>11-12-1990</date>
				<notInStock/>
			</product>
			<product name="Product123">
				<provider>Provider123</provider>
				<model>Model123</model>
				<color>Color123</color>
				<date>03-09-2099</date>
				<price>123.00</price>
			</product>
		</subcategory>
	</category>
	<category name="Category2">
		<subcategory name="Subcategory21">
			<product name="Product211">
				<provider>Provider211</provider>
				<model>Model211</model>
				<color>Color211</color>
				<date>01-01-2001</date>
				<notInStock/>
			</product>
			<product name="Product212">
				<provider>Provider212</provider>
				<model>Model212</model>
				<color>Color212</color>
				<date>03-03-2003</date>
				<price>101.01</price>
			</product>
			<product name="Product213">
				<provider>Provider213</provider>
				<model>Model213</model>
				<color>Color213</color>
				<date>03-05-2003</date>
				<price>113.00</price>
			</product>
		</subcategory>
	</category>
</products:categoryList>
